############################# English ############################
[en]
languageName = "En"
title = "OSCAR"
contentDir = "content/english" # content/english
weight = 1

[en.params]
########### footer content ##########
footer_menu_left = "Product"
#footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "Open Source Serverless Computing for Data-Processing Applications"

# Para cualquier otro parámetro personalizado que tengas, asegúrate de colocarlos bajo [en.params] también.

############################# Deutsch ############################
# Descomenta y ajusta los siguientes parámetros para el alemán si también necesitas hacer el cambio.
#[de]
#languageName = "De"
#title = "Bigspring Hugo"
#contentDir = "content/deutsch" # content/german
#weight = 2

#[de.params]
############ footer content ##########
#footer_menu_left = "Firma"
#footer_menu_middle = "Produkte"
#footer_menu_right = "Support"
#footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
